Repository Fifis-Organization/Brocoli-se, pull requests merged in 2021-09, with the labels that each got.

#1 Feature/colors and fonts
  BrocoliSe/BrocoliSe.xcodeproj/project.pbxproj
  BrocoliSe/BrocoliSe.xcworkspace/contents.xcworkspacedata
  BrocoliSe/BrocoliSe.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  BrocoliSe/BrocoliSe/Assets.xcassets/AppIcon.appiconset/1024.png
  BrocoliSe/BrocoliSe/Assets.xcassets/AppIcon.appiconset/120-1.png
  BrocoliSe/BrocoliSe/Assets.xcassets/AppIcon.appiconset/120.png
  BrocoliSe/BrocoliSe/Assets.xcassets/AppIcon.appiconset/180.png
  BrocoliSe/BrocoliSe/Assets.xcassets/AppIcon.appiconset/40.png
  BrocoliSe/BrocoliSe/Assets.xcassets/AppIcon.appiconset/58.png
  BrocoliSe/BrocoliSe/Assets.xcassets/AppIcon.appiconset/60.png
  BrocoliSe/BrocoliSe/Assets.xcassets/AppIcon.appiconset/80.png
  BrocoliSe/BrocoliSe/Assets.xcassets/AppIcon.appiconset/87.png
  BrocoliSe/BrocoliSe/Assets.xcassets/AppIcon.appiconset/Contents.json
  BrocoliSe/BrocoliSe/Assets.xcassets/Colors/Contents.json
  BrocoliSe/BrocoliSe/Assets.xcassets/Colors/background-color.colorset/Contents.json
  BrocoliSe/BrocoliSe/Assets.xcassets/Colors/blue-dark.colorset/Contents.json
  BrocoliSe/BrocoliSe/Assets.xcassets/Colors/green-medium.colorset/Contents.json
  BrocoliSe/BrocoliSe/Assets.xcassets/Colors/green-soft.colorset/Contents.json
  BrocoliSe/BrocoliSe/Assets.xcassets/Colors/red-custom.colorset/Contents.json
  BrocoliSe/BrocoliSe/Info.plist
  BrocoliSe/BrocoliSe/View/Colors/Colors.swift
  BrocoliSe/BrocoliSe/View/Fonts/Fonts.swift
  BrocoliSe/BrocoliSe/View/Fonts/Graviola-Regular.otf
  BrocoliSe/BrocoliSe/View/Fonts/GraviolaSoft-Medium.otf
  BrocoliSe/Podfile
  BrocoliSe/Podfile.lock
  BrocoliSe/Pods/Manifest.lock
  BrocoliSe/Pods/Pods.xcodeproj/project.pbxproj
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-Info.plist
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-acknowledgements.markdown
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-acknowledgements.plist
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-dummy.m
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-umbrella.h
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe.debug.xcconfig
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe.modulemap
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe.release.xcconfig
Labels: enhancement

#3 Feature/01 coordinators
  BrocoliSe/BrocoliSe.xcodeproj/project.pbxproj
  BrocoliSe/BrocoliSe/Assets.xcassets/TabBar/Contents.json
  BrocoliSe/BrocoliSe/Assets.xcassets/TabBar/album-icon.imageset/AlbumIcon.png
  BrocoliSe/BrocoliSe/Assets.xcassets/TabBar/album-icon.imageset/Contents.json
  BrocoliSe/BrocoliSe/Assets.xcassets/TabBar/daily-icon.imageset/Contents.json
  BrocoliSe/BrocoliSe/Assets.xcassets/TabBar/daily-icon.imageset/DailyIcon.png
  BrocoliSe/BrocoliSe/Coordinators/AppCoordinator.swift
  BrocoliSe/BrocoliSe/Coordinators/Coordinator.swift
  BrocoliSe/BrocoliSe/Coordinators/TabBarPage.swift
  BrocoliSe/BrocoliSe/Coordinators/TabCoordinator.swift
  BrocoliSe/BrocoliSe/SceneDelegate.swift
Labels: enhancement

#9 Feature/07 calendar
  BrocoliSe/BrocoliSe.xcodeproj/project.pbxproj
  BrocoliSe/BrocoliSe/Controller/ViewController.swift
  BrocoliSe/BrocoliSe/Info.plist
  BrocoliSe/BrocoliSe/View/Components/DiaryCardComponent.swift
  BrocoliSe/BrocoliSe/View/Components/DiaryTableViewCellComponent.swift
  BrocoliSe/BrocoliSe/View/Components/ProgressBarComponent.swift
  BrocoliSe/BrocoliSe/View/Scenes/DiaryScene.swift
  BrocoliSe/BrocoliSe/View/Scenes/Scenes.swift
  BrocoliSe/Podfile
  BrocoliSe/Podfile.lock
  BrocoliSe/Pods/Manifest.lock
  BrocoliSe/Pods/Pods.xcodeproj/project.pbxproj
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-acknowledgements.markdown
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-acknowledgements.plist
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-frameworks-Debug-input-files.xcfilelist
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-frameworks-Debug-output-files.xcfilelist
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-frameworks-Release-input-files.xcfilelist
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-frameworks-Release-output-files.xcfilelist
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-frameworks.sh
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe.debug.xcconfig
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe.release.xcconfig
Labels: enhancement

#12 Feature/09 actions lint
  .github/workflows/swiftlint.yml
Labels: enhancement

#18 Feature/04 core data
  BrocoliSe/BrocoliSe.xcodeproj/project.pbxproj
  BrocoliSe/BrocoliSe/AppDelegate.swift
  BrocoliSe/BrocoliSe/Controller/DiaryViewController.swift
  BrocoliSe/BrocoliSe/Controller/ViewController.swift
  BrocoliSe/BrocoliSe/Coordinators/FactoryControllers.swift
  BrocoliSe/BrocoliSe/Coordinators/OnboardingCoordinator.swift
  BrocoliSe/BrocoliSe/Coordinators/TabBarPage.swift
  BrocoliSe/BrocoliSe/Coordinators/TabCoordinator.swift
  BrocoliSe/BrocoliSe/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
  BrocoliSe/BrocoliSe/Model/CoreDataManager.swift
  BrocoliSe/BrocoliSe/Model/Model.swift
  BrocoliSe/BrocoliSe/Model/UseCases/EntityCreateProtocol.swift
  BrocoliSe/BrocoliSe/Model/UseCases/EntityFetchProtocol.swift
  BrocoliSe/BrocoliSe/Model/UseCases/EntitySaveProtocol.swift
  BrocoliSe/BrocoliSe/Utilities/StringExtension.swift
  BrocoliSe/BrocoliSe/View/Components/TextField.swift
  BrocoliSe/BrocoliSe/View/Scenes/DiaryScene.swift
  BrocoliSe/BrocoliSe/View/Scenes/Onboardings/Onboarding02.swift
Labels: enhancement

#22 Feature/16 pan gesture
  BrocoliSe/BrocoliSe/Model/UseCases/EntityFetchProtocol.swift
  BrocoliSe/BrocoliSe/View/Components/DiaryCardComponent.swift
  BrocoliSe/BrocoliSe/View/Components/FoodSelectorComponent.swift
  BrocoliSe/BrocoliSe/View/Scenes/DiaryScene.swift
Labels: enhancement

#26 Feature/07 calendar
  BrocoliSe/BrocoliSe/Controller/DiaryViewController.swift
  BrocoliSe/BrocoliSe/View/Components/DiaryCardComponent.swift
  BrocoliSe/BrocoliSe/View/Scenes/DiaryScene.swift
  BrocoliSe/Podfile
  BrocoliSe/Podfile.lock
  BrocoliSe/Pods/Manifest.lock
  BrocoliSe/Pods/Pods.xcodeproj/project.pbxproj
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe-frameworks.sh
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe.debug.xcconfig
  BrocoliSe/Pods/Target Support Files/Pods-BrocoliSe/Pods-BrocoliSe.release.xcconfig
Labels: enhancement

#28 Feature/20 modal recompensa coredata
  BrocoliSe/BrocoliSe/Controller/DiaryViewController.swift
  BrocoliSe/BrocoliSe/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
  BrocoliSe/BrocoliSe/View/Components/DiaryTableViewCellComponent.swift
  BrocoliSe/BrocoliSe/View/Scenes/DiaryScene.swift
Labels: enhancement

#29 Feature/07 calendar
  BrocoliSe/BrocoliSe.xcodeproj/project.pbxproj
  BrocoliSe/BrocoliSe/Controller/DiaryViewController.swift
  BrocoliSe/BrocoliSe/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
  BrocoliSe/BrocoliSe/Utilities/UIViewExtension.swift
  BrocoliSe/BrocoliSe/View/Components/DiaryCardComponent.swift
  BrocoliSe/BrocoliSe/View/Components/DiaryTableViewCellComponent.swift
  BrocoliSe/BrocoliSe/View/Scenes/DiaryScene.swift
  BrocoliSe/BrocoliSe/View/Scenes/Onboardings/Onboarding03.swift
  BrocoliSe/Podfile
  BrocoliSe/Podfile.lock
  BrocoliSe/Pods/Manifest.lock
Labels: enhancement

#30 setup
  BrocoliSe/BrocoliSe.xcodeproj/project.pbxproj
  BrocoliSe/BrocoliSe/Controller/AlbumViewController.swift
  BrocoliSe/BrocoliSe/Controller/DiaryViewController.swift
  BrocoliSe/BrocoliSe/View/Components/DiaryCardComponent.swift
  BrocoliSe/BrocoliSe/View/Components/ProgressBarComponent.swift
  BrocoliSe/BrocoliSe/View/Scenes/AlbumScene.swift
  BrocoliSe/BrocoliSe/View/Scenes/DiaryScene.swift
Labels: release

#35 Feature/84 label haptic autolayout
  BrocoliSe/BrocoliSe/Coordinators/TabCoordinator.swift
  BrocoliSe/BrocoliSe/Utilities/UIViewExtension.swift
  BrocoliSe/BrocoliSe/View/Components/DiaryCardComponent.swift
  BrocoliSe/BrocoliSe/View/Scenes/DiaryScene.swift
Labels: bug, enhancement

#36 Bugfix/header view
  BrocoliSe/BrocoliSe/View/Scenes/DiaryScene.swift
Labels: bug
